# Generated by Django 5.2.15 on 2026-06-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='package',
            name='date',
        ),
    ]
