# Generated by Django 5.2.15 on 2026-06-18 11:02

import django.db.models.deletion
import transportation.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trip_date', models.DateTimeField()),
                ('photo', models.ImageField(upload_to=transportation.models.bus_photo_path)),
                ('climate_control', models.CharField(choices=[('ac', 'AC'), ('non_ac', 'Non-AC')], max_length=10)),
                ('route_origin', models.CharField(max_length=100)),
                ('route_destination', models.CharField(max_length=100)),
                ('total_seats', models.PositiveIntegerField()),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['trip_date'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Charter Car', max_length=100)),
                ('trip_date', models.DateTimeField()),
                ('photo', models.ImageField(upload_to=transportation.models.car_photo_path)),
                ('climate_control', models.CharField(choices=[('ac', 'AC'), ('non_ac', 'Non-AC')], max_length=10)),
                ('capacity', models.PositiveIntegerField(choices=[(4, '4 Seats'), (12, '12 Seats'), (28, '28 Seats')])),
                ('return_date', models.DateTimeField(blank=True, help_text='Required for round trips only', null=True)),
                ('trip_type', models.CharField(choices=[('hourly', 'Hourly'), ('intercity_one_way', 'Intercity One-Way'), ('intercity_round_trip', 'Intercity Round Trip')], max_length=25)),
                ('price', models.DecimalField(decimal_places=2, help_text='Calculated by admin from trip type and duration', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['trip_date'],
            },
        ),
        migrations.CreateModel(
            name='BusBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash_on_arrival', 'Cash on Arrival'), ('pay_now', 'Pay Now')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coupon_code', models.CharField(blank=True, max_length=30)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_date', models.DateTimeField(help_text='Date/time the booked service takes place (UTC)')),
                ('terms_accepted', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('refund_percentage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('decline_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seat_numbers', models.CharField(help_text='Comma-separated seat numbers, e.g. 12,13,14', max_length=255)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='transportation.bus')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash_on_arrival', 'Cash on Arrival'), ('pay_now', 'Pay Now')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coupon_code', models.CharField(blank=True, max_length=30)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_date', models.DateTimeField(help_text='Date/time the booked service takes place (UTC)')),
                ('terms_accepted', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('refund_percentage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('decline_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='transportation.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
