# Generated by Django 5.2.15 on 2026-06-25 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['trip_type']},
        ),
        migrations.RemoveField(
            model_name='car',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='trip_date',
        ),
        migrations.AddField(
            model_name='carbooking',
            name='return_date',
            field=models.DateTimeField(blank=True, help_text='Required for round trips only', null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='trip_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
