# Generated by Django 5.2.15 on 2026-06-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0002_alter_car_options_remove_car_return_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbooking',
            name='return_date',
        ),
    ]
